// Generated by CoffeeScript 1.12.4
(function() {
  var Hiyositiyau, J;

  J = require('julian-date');

  Hiyositiyau = Hiyositiyau = (function() {
    function Hiyositiyau() {
      this.name = 3;
    }

    Hiyositiyau.prototype.now = function() {
      var j;
      j = new J;
      return j.julian() - 2375839.4583333335;
    };

    Hiyositiyau.prototype.printNow = function() {
      return alert((new Hiyositiyau).now());
    };

    return Hiyositiyau;

  })();

}).call(this);
